[book]
authors = ["thecodewarrior"]
language = "en"
multilingual = false
src = "src"
title = "LibrarianLib"

[output.html]
curly-quotes = true

[output.html.playground.boring-prefixes]
java = "~"
kotlin = "~"